# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\ckhoi\PycharmProjects\HexoPubAssistant\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(610, 292)
        font = QtGui.QFont()
        font.setFamily("GenWanMin TW TTF Medium")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ICON/hexo logo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(233, 233, 225);\n"
"selection-background-color: rgb(199, 197, 184);\n"
"font: 57 10pt \"GenWanMin TW TTF Medium\";")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 111, 16))
        self.label.setObjectName("label")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 40, 591, 92))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.blog_title = QtWidgets.QLabel(self.formLayoutWidget)
        self.blog_title.setObjectName("blog_title")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.blog_title)
        self.blog_title_LineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.blog_title_LineEdit.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.blog_title_LineEdit.setReadOnly(True)
        self.blog_title_LineEdit.setObjectName("blog_title_LineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.blog_title_LineEdit)
        self.blog_category = QtWidgets.QLabel(self.formLayoutWidget)
        self.blog_category.setObjectName("blog_category")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.blog_category)
        self.blog_category_LineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.blog_category_LineEdit.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.blog_category_LineEdit.setReadOnly(True)
        self.blog_category_LineEdit.setObjectName("blog_category_LineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.blog_category_LineEdit)
        self.blog_tag = QtWidgets.QLabel(self.formLayoutWidget)
        self.blog_tag.setObjectName("blog_tag")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.blog_tag)
        self.blog_tag_LineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.blog_tag_LineEdit.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.blog_tag_LineEdit.setReadOnly(True)
        self.blog_tag_LineEdit.setObjectName("blog_tag_LineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.blog_tag_LineEdit)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 130, 171, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.blog_status_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.blog_status_label.setText("")
        self.blog_status_label.setObjectName("blog_status_label")
        self.horizontalLayout.addWidget(self.blog_status_label)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 180, 106, 26))
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(220, 140, 101, 16))
        self.label_3.setObjectName("label_3")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(330, 130, 271, 101))
        self.listWidget.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.listWidget.setObjectName("listWidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 610, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.action_5 = QtWidgets.QAction(MainWindow)
        self.action_5.setObjectName("action_5")
        self.scan_categories = QtWidgets.QAction(MainWindow)
        self.scan_categories.setObjectName("scan_categories")
        self.help = QtWidgets.QAction(MainWindow)
        self.help.setObjectName("help")
        self.about = QtWidgets.QAction(MainWindow)
        self.about.setObjectName("about")
        self.open_config_file = QtWidgets.QAction(MainWindow)
        self.open_config_file.setObjectName("open_config_file")
        self.menu.addAction(self.action)
        self.menu.addAction(self.action_2)
        self.menu.addAction(self.action_3)
        self.menu.addSeparator()
        self.menu.addAction(self.action_5)
        self.menu_2.addAction(self.scan_categories)
        self.menu_2.addAction(self.open_config_file)
        self.menu_3.addAction(self.help)
        self.menu_3.addAction(self.about)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())

        self.retranslateUi(MainWindow)
        self.action_5.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Hexo博客发布助手"))
        self.label.setText(_translate("MainWindow", "博文信息："))
        self.blog_title.setText(_translate("MainWindow", "标题："))
        self.blog_category.setText(_translate("MainWindow", "分类："))
        self.blog_tag.setText(_translate("MainWindow", "Tag："))
        self.label_2.setText(_translate("MainWindow", "博文状态："))
        self.pushButton.setText(_translate("MainWindow", "打开博文以编辑"))
        self.label_3.setText(_translate("MainWindow", "现有博文分类："))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menu_2.setTitle(_translate("MainWindow", "设置"))
        self.menu_3.setTitle(_translate("MainWindow", "帮助"))
        self.action.setText(_translate("MainWindow", "新建博文"))
        self.action.setToolTip(_translate("MainWindow", "使用hexo new创建一篇新文章"))
        self.action_2.setText(_translate("MainWindow", "预览"))
        self.action_2.setToolTip(_translate("MainWindow", "使用hexo s预览"))
        self.action_3.setText(_translate("MainWindow", "发布"))
        self.action_3.setToolTip(_translate("MainWindow", "使用hexo d发布文章"))
        self.action_5.setText(_translate("MainWindow", "退出"))
        self.scan_categories.setText(_translate("MainWindow", "手动扫描全部分类"))
        self.scan_categories.setToolTip(_translate("MainWindow", "扫描现有博文的全部分类"))
        self.help.setText(_translate("MainWindow", "打开帮助文本"))
        self.about.setText(_translate("MainWindow", "关于本软件"))
        self.open_config_file.setText(_translate("MainWindow", "打开配置文件"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

